#!/bin/bash

DIR=/home/salil/.config/picom.conf
TOG1="  normal = { blur-background = true; };"
TOG0="  normal = { blur-background = false; };"
CUR_STATE=$(grep "normal = { blur-background =" $DIR)

if [[ $CUR_STATE == "$TOG1" ]]; then sed -i "s/$TOG1/$TOG0/g" $DIR; else sed -i "s/$TOG0/$TOG1/g" $DIR; fi


TOG1="  dock   = { blur-background = true; };"
TOG0="  dock   = { blur-background = false; };"
CUR_STATE=$(grep "dock   = { blur-background =" $DIR)

if [[ $CUR_STATE == "$TOG1" ]]; then sed -i "s/$TOG1/$TOG0/g" $DIR; else sed -i "s/$TOG0/$TOG1/g" $DIR; fi
